//Generated by DbSharpApplication.https://github.com/higty/higlabo.netstandard/tree/master/Tools/DbSharp
using System;
using System.Data;
using System.Text;
using HigLabo.DbSharp;

namespace HigLabo.DbSharpSample.SqlServer
{
    public partial class IdentityTable
    {
        public interface IRecord
        {
            Int32 IntColumn { get; set; }
            String NVarCharColumn { get; set; }
        }
    }
}
