//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HigLabo.DbSharpApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HigLabo.DbSharpApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AllowNull に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowNull {
            get {
                return ResourceManager.GetString("AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ColumnName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CommandService is executing.Please wait until CommandService is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandServiceExecuting {
            get {
                return ResourceManager.GetString("CommandServiceExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConnectionString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not connect database.Please eunsure your connection string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DbType {
            get {
                return ResourceManager.GetString("DbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable ForeignKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableForeignKey {
            get {
                return ResourceManager.GetString("DisableForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnumName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnumName {
            get {
                return ResourceManager.GetString("EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnumValues に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnumValues {
            get {
                return ResourceManager.GetString("EnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Add {
            get {
                return ResourceManager.GetString("Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Ignore list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddToIgnoreList {
            get {
                return ResourceManager.GetString("Menu_AddToIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Connect {
            get {
                return ResourceManager.GetString("Menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy ResultSet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_CopyResultSet {
            get {
                return ResourceManager.GetString("Menu_CopyResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete Object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DeleteObject {
            get {
                return ResourceManager.GetString("Menu_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete _Object and Add to ignore list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DeleteObjectAndAddToIgnoreList {
            get {
                return ResourceManager.GetString("Menu_DeleteObjectAndAddToIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Execute {
            get {
                return ResourceManager.GetString("Menu_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Generate C# Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_GenerateCSharpCode {
            get {
                return ResourceManager.GetString("Menu_GenerateCSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate S_qlScript に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_GenerateSqlScript {
            get {
                return ResourceManager.GetString("Menu_GenerateSqlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get _All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_GetAll {
            get {
                return ResourceManager.GetString("Menu_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import _StoredProcedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ImportStoredProcedure {
            get {
                return ResourceManager.GetString("Menu_ImportStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import _Table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ImportTable {
            get {
                return ResourceManager.GetString("Menu_ImportTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Updated Object and Generate Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ImportUpdatedObjectAndGenerateFiles {
            get {
                return ResourceManager.GetString("Menu_ImportUpdatedObjectAndGenerateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import _UserDefinedTableType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ImportUserDefinedTableType {
            get {
                return ResourceManager.GetString("Menu_ImportUserDefinedTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Manage Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ManageConnection {
            get {
                return ResourceManager.GetString("Menu_ManageConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Ignore list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ManageIgnoreList {
            get {
                return ResourceManager.GetString("Menu_ManageIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_OpenFile {
            get {
                return ResourceManager.GetString("Menu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu_Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Other {
            get {
                return ResourceManager.GetString("Menu_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Read Database Schema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ReadDatabaseSchema {
            get {
                return ResourceManager.GetString("Menu_ReadDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove from list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_RemoveFromList {
            get {
                return ResourceManager.GetString("Menu_RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save _As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select _All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_SelectAll {
            get {
                return ResourceManager.GetString("Menu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _StoredProcedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_StoredProcedure {
            get {
                return ResourceManager.GetString("Menu_StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Table {
            get {
                return ResourceManager.GetString("Menu_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _UserDefinedTableType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_UserDefinedTableType {
            get {
                return ResourceManager.GetString("Menu_UserDefinedTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select connection strings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSelectConnectionString {
            get {
                return ResourceManager.GetString("PleaseSelectConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Precision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrimaryKey に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessCompleted {
            get {
                return ResourceManager.GetString("ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StoredProcedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoredProcedure {
            get {
                return ResourceManager.GetString("StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no object altered after last import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThereIsNoObjectAlteredAfterLastProcess {
            get {
                return ResourceManager.GetString("ThereIsNoObjectAlteredAfterLastProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no object deleted after last import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThereIsNoObjectDeletedAfterLastProcess {
            get {
                return ResourceManager.GetString("ThereIsNoObjectDeletedAfterLastProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no object to delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThereIsNoObjectToDelete {
            get {
                return ResourceManager.GetString("ThereIsNoObjectToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimeZone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserDefinedTableType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDefinedTableType {
            get {
                return ResourceManager.GetString("UserDefinedTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Table feature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseTableFeature {
            get {
                return ResourceManager.GetString("UseTableFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table feature is unable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseTableFeatureUnableText {
            get {
                return ResourceManager.GetString("UseTableFeatureUnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value for test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueForTest {
            get {
                return ResourceManager.GetString("ValueForTest", resourceCulture);
            }
        }
    }
}
