//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HigLabo.DbSharpApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HigLabo.DbSharpApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowNull.
        /// </summary>
        public static string AllowNull {
            get {
                return ResourceManager.GetString("AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnName.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandService is executing.Please wait until CommandService is completed..
        /// </summary>
        public static string CommandServiceExecuting {
            get {
                return ResourceManager.GetString("CommandServiceExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect database.Please eunsure your connection string..
        /// </summary>
        public static string ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DbType {
            get {
                return ResourceManager.GetString("DbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumName.
        /// </summary>
        public static string EnumName {
            get {
                return ResourceManager.GetString("EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumValues.
        /// </summary>
        public static string EnumValues {
            get {
                return ResourceManager.GetString("EnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Menu_Add {
            get {
                return ResourceManager.GetString("Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect.
        /// </summary>
        public static string Menu_Connect {
            get {
                return ResourceManager.GetString("Menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Object.
        /// </summary>
        public static string Menu_DeleteObject {
            get {
                return ResourceManager.GetString("Menu_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Execute.
        /// </summary>
        public static string Menu_Execute {
            get {
                return ResourceManager.GetString("Menu_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generate C# Code.
        /// </summary>
        public static string Menu_GenerateCSharpCode {
            get {
                return ResourceManager.GetString("Menu_GenerateCSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate S_qlScript.
        /// </summary>
        public static string Menu_GenerateSqlScript {
            get {
                return ResourceManager.GetString("Menu_GenerateSqlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get _All.
        /// </summary>
        public static string Menu_GetAll {
            get {
                return ResourceManager.GetString("Menu_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ImportObject.
        /// </summary>
        public static string Menu_ImportObject {
            get {
                return ResourceManager.GetString("Menu_ImportObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import _StoredProcedure.
        /// </summary>
        public static string Menu_ImportStoredProcedure {
            get {
                return ResourceManager.GetString("Menu_ImportStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import _Table.
        /// </summary>
        public static string Menu_ImportTable {
            get {
                return ResourceManager.GetString("Menu_ImportTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Updated Object and Generate Files.
        /// </summary>
        public static string Menu_ImportUpdatedObjectAndGenerateFiles {
            get {
                return ResourceManager.GetString("Menu_ImportUpdatedObjectAndGenerateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import _UserDefinedTableType.
        /// </summary>
        public static string Menu_ImportUserDefinedTableType {
            get {
                return ResourceManager.GetString("Menu_ImportUserDefinedTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage _Connection.
        /// </summary>
        public static string Menu_ManageConnection {
            get {
                return ResourceManager.GetString("Menu_ManageConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open File.
        /// </summary>
        public static string Menu_OpenFile {
            get {
                return ResourceManager.GetString("Menu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent Files.
        /// </summary>
        public static string Menu_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string Menu_SelectAll {
            get {
                return ResourceManager.GetString("Menu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StoredProcedure.
        /// </summary>
        public static string Menu_StoredProcedure {
            get {
                return ResourceManager.GetString("Menu_StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Table.
        /// </summary>
        public static string Menu_Table {
            get {
                return ResourceManager.GetString("Menu_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UserDefinedTableType.
        /// </summary>
        public static string Menu_UserDefinedTableType {
            get {
                return ResourceManager.GetString("Menu_UserDefinedTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select connection strings.
        /// </summary>
        public static string PleaseSelectConnectionString {
            get {
                return ResourceManager.GetString("PleaseSelectConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select item.
        /// </summary>
        public static string PleaseSelectItem {
            get {
                return ResourceManager.GetString("PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey.
        /// </summary>
        public static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        public static string ProcessCompleted {
            get {
                return ResourceManager.GetString("ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all item.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedure.
        /// </summary>
        public static string StoredProcedure {
            get {
                return ResourceManager.GetString("StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no object altered after last import.
        /// </summary>
        public static string ThereIsNoObjectAlteredAfterLastProcess {
            get {
                return ResourceManager.GetString("ThereIsNoObjectAlteredAfterLastProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no object deleted after last import.
        /// </summary>
        public static string ThereIsNoObjectDeletedAfterLastProcess {
            get {
                return ResourceManager.GetString("ThereIsNoObjectDeletedAfterLastProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no object to delete.
        /// </summary>
        public static string ThereIsNoObjectToDelete {
            get {
                return ResourceManager.GetString("ThereIsNoObjectToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedTableType.
        /// </summary>
        public static string UserDefinedTableType {
            get {
                return ResourceManager.GetString("UserDefinedTableType", resourceCulture);
            }
        }
    }
}
